version: "3.9"
services:
    keycloak:
        build: .
        container_name: keycloakS
        environment: 
          - KEYCLOAK_USER=admin
          - KEYCLOAK_PASSWORD=admin
        ports:
          - "8180:8080"