version: '3'
services:
  app1:
    build: ./nlp
    ports:
    - "5003:5000"
    volumes:
    - shared_files:/nlp/tmp_files
  app2:
    build: ./nlp
    ports:
    - "5004:5000"
    volumes:
    - shared_files:/nlp/tmp_files
  nginx:
    build: ./nginx 
    ports:
    - "8081:80"
    volumes:
    - shared_files:/nlp/tmp_files
    depends_on:
      - app1
      - app2


volumes:
  shared_files:
    external: true