version: '3'
services:
  app1:
    build: ./nlp
    ports:
    - "5003:5000"
  app2:
    build: ./nlp
    ports:
    - "5004:5000"
  nginx:
    build: ./nginx 
    ports:
    - "8081:80"
    depends_on:
      - app1
      - app2
